---
- hosts: all
  become: yes
  tasks: 
  - name: install apache on redhat
    yum:
       name: httpd
       state: present
       when: ansible_os_family == "redhat"
  - name: install apache on ubunttu
    apt:
       name: appache2
       state: present
       when: ansible_os_family == "ubuntu"
